#!/usr/bin/env python
"""The DME's protections (ms45emu/protections.py, docs/protections.md).

    .venv/bin/python tools/protections.py --table docs/protections-checks.md     # every check, statically
    .venv/bin/python tools/protections.py --pair patched                          # what it trips vs the stock pair
    .venv/bin/python tools/protections.py --flash X_Flash.bin --mpc X_MPC.bin --rpm 800 --seconds 2 --key-off
    .venv/bin/python tools/protections.py --pair stock --no-compare               # just the stock pair's own report

The run boots the pair, lets it settle, then runs the scenario (the
crank at --rpm, the E46 peers on the bus, --key-off for the after-run)
with the fault reporter probed and the limp-home flags, the engine
state, the watchdog and the exception path watched. The stock pair is
run the same way and the difference printed: faults the custom pair
fails that the stock one does not, flags it sets, a reset.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from ms45emu import load_pair                           # noqa: E402
from ms45emu.board import Board                         # noqa: E402
from ms45emu.image import Pair, ENV_NAMES               # noqa: E402
from ms45emu.funcmap import FunctionMap                 # noqa: E402
from ms45emu.faults import Faults                       # noqa: E402
from ms45emu.xdf import Xdf                             # noqa: E402
from ms45emu.protections import Checks, Reactions, compare   # noqa: E402


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--pair", default="patched", choices=list(ENV_NAMES))
    ap.add_argument("--flash")
    ap.add_argument("--mpc")
    ap.add_argument("--base", default="stock", choices=list(ENV_NAMES), help="the pair to compare with (default stock)")
    ap.add_argument("--no-compare", action="store_true")
    ap.add_argument("--table", metavar="FILE.md", help="write the static table of checks and stop")
    ap.add_argument("--rpm", type=float, default=800)
    ap.add_argument("--speed", type=float, default=0, metavar="KMH")
    ap.add_argument("--seconds", type=float, default=1.0)
    ap.add_argument("--settle", type=float, default=0.5)
    ap.add_argument("--key-off", action="store_true", help="switch the ignition off after settling: the after-run")
    ap.add_argument("--mips", type=int, default=40)
    args = ap.parse_args()

    if args.flash and args.mpc:
        with open(args.flash, "rb") as f, open(args.mpc, "rb") as m:
            name = os.path.basename(args.flash).rsplit(".", 1)[0].replace("_Flash", "")
            pair = Pair(f.read(), m.read(), name)
    else:
        pair = load_pair(args.pair)
    fm = FunctionMap(pair)
    faults = Faults(pair)

    if args.table:
        checks = Checks(fm, Xdf.find(pair), faults)
        with open(args.table, "w") as f:
            f.write(f"# Checks in program {pair.program_id.decode('latin1')}\n\n"
                    "Generated by `tools/protections.py --table`: every routine that reports a fault "
                    "(by the index it passes to `fault_report`) or writes a limp-home flag or the engine state, "
                    "the OS task it runs under, the calibration items it reads (XDF names), the RAM it reads and writes.\n\n")
            f.write(checks.markdown() + "\n")
        print(f"{len(checks.checks)} checks written to {args.table}")
        return

    def run(p):
        r = Reactions(Board(p, mips=args.mips), FunctionMap(p) if p is not pair else fm)
        print(f"{p.name}: booting and running {args.seconds:g} s at {args.rpm:g} rpm" + (", key off" if args.key_off else "") + "...", flush=True)
        r.scenario(rpm=args.rpm, seconds=args.seconds, settle=args.settle, speed=args.speed, key_off=args.key_off)
        return r

    mine = run(pair)
    print(mine.report(faults))
    if args.no_compare or pair.name == args.base:
        return
    base = run(load_pair(args.base))
    print()
    print(base.report(faults))
    print()
    diff = compare(base, mine, faults)
    if diff:
        print(f"{pair.name} vs {args.base}:")
        for line in diff:
            print("  " + line)
    else:
        print(f"{pair.name} trips nothing that {args.base} does not.")


if __name__ == "__main__":
    main()
